### ISSUE TITLE
Not working with node

### ISSUE THREAD

**Issue by vschoettke** [peterolson/BigRational.js#15]
It's impossible to require big-rational version 0.9.9 and 0.9.10 with node/io.js because you try to set a global variable (bigInt) and use strict mode, which is impossible. 

Here's the output
```
> var a = require('big-rational')
ReferenceError: bigInt is not defined
    at /home/node/test/node_modules/big-rational/BigRational.js:4:16
    at Object.<anonymous> (/home/node/egn-deploy/test/node_modules/big-rational/BigRational.js:278:3)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:154:27)
```

**Comment by peterolson** [comment]
Thanks, I've merged a pull request resolving the issue, I'll update the npm package tomorrow morning.

**Comment by peterolson** [comment]
The issue should be fixed now. Let me know if the problem persists.
